# Generated by Django 3.2 on 2021-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiChans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('subscribers', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EurovisionCelebrities',
        ),
    ]
